import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 0.0,
      numReviews: 0,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 0.0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 0.0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
      // _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 0.0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
      // _id: '5',
      name: 'Basic Cuban Shirt',
      slug: 'basic-cuban-shirt',
      category: 'Shirts',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 0.0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
      // _id: '6',
      name: 'Orchid Flower Shirt',
      slug: 'orchid-flower-shirt',
      category: 'Shirts',
      image: '/images/p6.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 0.0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
      // _id: '7',
      name: 'Long sleeve shirt',
      slug: 'long-sleeve-shirt',
      category: 'Shirts',
      image: '/images/p7.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 0.0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
      // _id: '8',
      name: 'Baggy Khaki Pant',
      slug: 'baggy-khaki-pant',
      category: 'Pants',
      image: '/images/p8.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 0.0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
      // _id: '9',
      name: 'Three Hundred Basic Pants In Black',
      slug: 'three-hundred-basic-pants-in-black',
      category: 'Pants',
      image: '/images/p9.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 0.0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
      // _id: '10',
      name: 'Pants With Side Zipper In Black',
      slug: 'pants-with-side-zipper-in-black',
      category: 'Pants',
      image: '/images/p10.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 0.0,
      numReviews: 0,
      description: 'high quality product',
    },
  ],
};
export default data;
